# trained model, inference results, visualised images will be saved in model_dir
model_dir: ../shokusei_test/FL_CRF

label_file_path: ../taniguchi-j_stg318/omonogawa_shokusei/train_data/label_list.csv
train_x_dirs:
    - ../taniguchi-j_stg318/omonogawa_shokusei/train_data
    # - path/to/train_data_dir2
    #- path/to/train_data1.h5
    #- path/to/train_data2.h5
train_y_dirs:
    - ../taniguchi-j_stg318/omonogawa_shokusei/train_y
valid_x_dirs:
    - ../taniguchi-j_stg318/omonogawa_shokusei/train_data
    # - path/to/valid_data_dir2
    #- path/to/valid_data1.h5
    #- path/to/valid_data2.h5
valid_y_dirs:
    - ../taniguchi-j_stg318/omonogawa_shokusei/train_y


# below is to inference and visualise.
test_x_dirs:
    # - ../taniguchi-j_stg318/omonogawa_shokusei/valid_data/H27出水前画角
    - ../taniguchi-j_stg318/omonogawa_shokusei/test/x
    # - path/to/test_data_dir2
#if you don't use the value, write "~" like below.
#test_data_paths: ~

which_to_inference:
    - train
    - valid
    - test
which_to_visualise:
    - train
    - valid
    - test

# below is training setting
# choose one for output_activation.
# softmax: one pixel belong to one category.
# sigmoid: one pixel can belong to two or more categories.
output_activation: softmax
batch_size: 4
n_epochs: 6000
use_devices: "0" # if you want to do distributed learning, write like "0,1,2".
image_size: [512,512]
optimizer: Adam #Adam or Nadam or SGD
add_CRFasRNN: True

# Choose one for loss function.
# CE: cross entropy
# WCE: weighted cross entropy
# FL: focal loss
# GDL: generalized dice loss
loss: FL

# Choose one fore metrics
# IoU: Intersection over Union. Jaccard index.
# F1score : F1score. F measure. Dice coefficient.
metrics: IoU

# True, if you want to check metrics for each label.
check_categorical_metrics: True

# The length of class_weight must be same as the number of labels.
# If you write class_weight to "~", treated all classes as having same weight.
# If sum of class_weigths is not 1, automaticaly set as such.
class_weight: ~
#class_weight:
#    - 0.1
#    - 0.8
#    - 0.1
#class_weight:
#    - 100
#    - 200
# True or False
use_tensorboard: True
